<a href="https://colab.research.google.com/github/mvadrev/reinforcementLearning/blob/main/10_armed_bandit_lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
from numpy.core.fromnumeric import argmax
import numpy as np 
class tenBandit():
       def __init__(self, arms, epsilon):

         self.arms = np.array(range(arms), dtype='int')
         self._initValues =  np.random.normal(0,1, size=10) #q-star
         self.N = np.zeros(self.arms.size, dtype='int')
         self.epsilon = epsilon
         self.reward = np.zeros(self.arms.size)
         self.actionCountLog = np.zeros(self.arms.size)

         print(self.arms, self._initValues, self.N)

       def action(self, arm): 
         value = self._initValues[arm]
         return np.random.normal(value, 1)

       

In [26]:
a = tenBandit(10, 1)



[0 1 2 3 4 5 6 7 8 9] [ 1.31295898  1.23081282  1.17801537 -1.40460379  1.19313921 -0.22546198
 -2.23649845 -1.53767791  0.8574579  -0.091097  ] [0 0 0 0 0 0 0 0 0 0]


In [43]:
def e_greedy(bandit, e, T):
         # Run code T times
         resultsForgraph = []
         for i in range(T):
            if (np.random.random() > a.epsilon):
              print("exploring...", np.random.choice(a.arms))
              a.actionCountLog[np.random.choice(a.arms)] += 1 # Add selected action to actionCountLog
              rewx = a.action(np.random.choice(a.arms))
              # update values of actions
              newQ = a._initValues[np.random.choice(a.arms)] + (1/a.actionCountLog[np.random.choice(a.arms)] * (rewx - a._initValues[np.random.choice(a.arms)] ))
              resultsForgraph.append(a._initValues)
            else:
              print("exploiting..", argmax(a._initValues)) # Select 
              a.actionCountLog[argmax(a._initValues)] += 1 # Add selected action to actionCountLog
              rewy = a.action(argmax(a._initValues))
              # update values of actions
              newQQ = a._initValues[argmax(a._initValues)] + (1/a.actionCountLog[argmax(a._initValues)] * rewy - a._initValues[argmax(a._initValues)])
              resultsForgraph.append(a._initValues)
         return resultsForgraph
            


In [44]:
a.action(1)

1.6285000961432001

In [46]:
e_greedy(a,0.01,10)

exploiting.. 0
exploiting.. 0
exploiting.. 0
exploiting.. 0
exploiting.. 0
exploiting.. 0
exploiting.. 0
exploiting.. 0
exploiting.. 0
exploiting.. 0


[array([ 1.31295898,  1.23081282,  1.17801537, -1.40460379,  1.19313921,
        -0.22546198, -2.23649845, -1.53767791,  0.8574579 , -0.091097  ]),
 array([ 1.31295898,  1.23081282,  1.17801537, -1.40460379,  1.19313921,
        -0.22546198, -2.23649845, -1.53767791,  0.8574579 , -0.091097  ]),
 array([ 1.31295898,  1.23081282,  1.17801537, -1.40460379,  1.19313921,
        -0.22546198, -2.23649845, -1.53767791,  0.8574579 , -0.091097  ]),
 array([ 1.31295898,  1.23081282,  1.17801537, -1.40460379,  1.19313921,
        -0.22546198, -2.23649845, -1.53767791,  0.8574579 , -0.091097  ]),
 array([ 1.31295898,  1.23081282,  1.17801537, -1.40460379,  1.19313921,
        -0.22546198, -2.23649845, -1.53767791,  0.8574579 , -0.091097  ]),
 array([ 1.31295898,  1.23081282,  1.17801537, -1.40460379,  1.19313921,
        -0.22546198, -2.23649845, -1.53767791,  0.8574579 , -0.091097  ]),
 array([ 1.31295898,  1.23081282,  1.17801537, -1.40460379,  1.19313921,
        -0.22546198, -2.23649845, -1.53

In [41]:
a.actionCountLog

array([12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [ ]:
a.ac